### ISSUE TITLE
Crash when i Rescue up by a bot 

### ISSUE THREAD

**Issue by DoctorKoKoDaYo** [segabl/pd2-useful-bots#1]
Application has crashed: C++ exception
mods/pd2-useful-bots-master/lua/teamailogicassault.lua:4: attempt to call method 'char_tweak' (a nil value)

SCRIPT STACK

_interact_check() @mods/[更好的AI]Better Bots/betterbots.lua:1012
original() @mods/[更好的AI]Better Bots/betterbots.lua:1023
_set_attention_obj() @mods/base/req/core/Hooks.lua:265
clbk() lib/units/player_team/logics/teamailogictravel.lua:199
_execute_queued_task() lib/managers/enemymanager.lua:562
_update_queued_tasks() @mods/Full Speed Swarm/lua/enemymanager.lua:29
update() lib/managers/enemymanager.lua:51
original() lib/setups/gamesetup.lua:744
update() @mods/base/req/core/Hooks.lua:265
_update() lib/setups/networkgamesetup.lua:21
update() @mods\PocoHud3\poco\common.lua:310
core/lib/setups/coresetup.lua:557

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlDosSearchPath_Ustr                               
                         ntdll  (???)     RtlFreeHeap                                         
                         ntdll  (???)     RtlSetLastWin32Error                                
                    KERNELBASE  (???)     CreateFileW                                         
                    KERNELBASE  (???)     CreateFileW                                         
                         ntdll  (???)     ZwQueryVirtualMemory                                
                    KERNELBASE  (???)     VirtualQueryEx                                      
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

**Comment by segabl** [comment]
I suggest not using it in combination with better bots. If you still get the crash without it, update this issue please.
