### ISSUE TITLE
Feature Request - Stay after Inspired

### ISSUE THREAD

**Issue by IsoiKim** [segabl/pd2-useful-bots#10]
Currently, bots will start to follow the player that inspired them, as the game treats using Inspire the same as calling someone over. This means that when they are helped up with Inspire, they will no longer guard an area or follow the player you want them to.

If possible, I'd suggest making the bots ignore follow commands while downed to hopefully change that behaviour.

Another small change that'd be nice but unnecessary would be making the Inspire boost skill unusable on bots, since they don't benefit from it.

**Comment by segabl** [comment]
I'll have a look at this, sounds like it should be simple to fix
