### ISSUE TITLE
coplogictravel.lua crash with unknown reason

### ISSUE THREAD

**Issue by IsoiKim** [segabl/pd2-useful-bots#11]
Another one I can't seem to reproduce. Happened on one of the window roofs on The Bomb: Dockyard when I told the bot to stay still. I noticed I see no mention of this being caused by the mod, but I have no other mods that modify coplogictravel.lua.

### Crash Log:
```
----------------------------------------------------------------------

Wed Jan 11 01:46:15 2023


Application has crashed: C++ exception
[string "lib/units/enemies/cop/logics/coplogictravel.lua"]:1581: attempt to index a nil value



SCRIPT STACK

update() lib/units/enemies/cop/logics/coplogictravel.lua:235
lib/units/enemies/cop/copbrain.lua:234


-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlDosSearchPath_Ustr                               
                         ntdll  (???)     RtlRestoreLastWin32Error                            
                         ntdll  (???)     ZwQueryVirtualMemory                                
                    KERNELBASE  (???)     VirtualQueryEx                                      
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.134.165
	CPU : 12th Gen Intel(R) Core(TM) i7-12700K (10 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce RTX 3070 Ti / nvldumd.dll[31.0.15.2802]
	Language : english
	Memory :     32538MB 116KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Razer Inc. (Headphones (Razer Nari - Game))
```

**Comment by segabl** [comment]
Hard to say what went wrong there, potentially less chance to happen in the next version

**Comment by segabl** [comment]
were they stopped or following?

**Comment by segabl** [comment]
Any other AI related mods?

**Comment by segabl** [comment]
when and where on the map did this occur approximately?

**Comment by segabl** [comment]
you may want to try the [upcoming version](https://github.com/segabl/pd2-useful-bots/files/10417895/Useful.Bots.zip) and check if this one still crashes you

**Comment by segabl** [comment]
I finally had this happen so I'm gonna try and reproduce. Were all the instances of it happening to you in multiplayer sessions with other people?

**Comment by segabl** [comment]
if you could put the contents of this file at the top of useful bots own coplogictravel, that would help me figure out whats causing it easier
[coplogictravel.zip](https://github.com/segabl/pd2-useful-bots/files/10460964/coplogictravel.zip)

**Comment by segabl** [comment]
it's weird cause I got the exact same crash today when playing with a friend. so my assumption is that it's either not happening in solo or not happening in my overhaul (streamlined heisting). I did have some assumptions about what might be causing it though in the meantime so adding the thing i sent shouldn't be necessary anymore. I'll keep this open though until I can confirm the latest change fixed it for good.

**Comment by segabl** [comment]
Like I said it should hopefully be fine now so no reason to try and reproduce it, I didn't manage to reproduce it in 2 hours

**Comment by segabl** [comment]
yeah weird, isn't it. the joy of hard to reproduce crashes

**Comment by segabl** [comment]
and that's with the current version? that should list a different callstack at least, weird

**Comment by segabl** [comment]
yeah version number did not change, I usually forget about that for small fixes

**Comment by segabl** [comment]
I suppose so. Can always reopen if it somehow happens again
