### ISSUE TITLE
Movement animations interrupted by hold command

### ISSUE THREAD

**Issue by IsoiKim** [segabl/pd2-useful-bots#12]
Bots have their movement animations interrupted when told to hold, causing them to float. This applies to all movement animations, i.e. jumps, rappels, wall climbs, slides, etc. and can (but usually won't) get the bots stuck.

Video Demonstration:
https://youtu.be/6htztgiLhSw

**Comment by segabl** [comment]
Should be fixed in the next version

**Comment by segabl** [comment]
Hm, maybe that wasn't enough then, well for now dont tell them to hold while they are in a special animation until I can look into this further

**Comment by segabl** [comment]
this should be mostly fixed now. i say mostly cause there's still a rare vanilla issue where interrupting a nav link will make them warp back to the start of it but that's a base game issue that affects any npc and would be kinda out of scope to fix in this mod.
