### ISSUE TITLE
Feature Request - Don't shoot shield's front

### ISSUE THREAD

**Issue by ghost** [segabl/pd2-useful-bots#13]
Would it be possible to either have an optional tickbox for if bots will shoot shields from the front so that the player can tick it on or off depending on if they have piercing rounds equipped or even better have it automatically detect whether the bot is using a sniper rifle or the piercing round perk is enabled?

I assume this would be quite challenging to implement it, especially with having the behaviour trigger based on what's equipped, and that even more if only one of the bots has a piercing weapon.

From my point of view, feel free to disregard this if it's not worth your time. It's not that big of an issue if you keep it always in mind in your crew setup.

**Comment by segabl** [comment]
this is already vanilla behavior and also part of useful bots, the priorities for enemies that have their line of sight obstructed by shields is multiplied by 0.01 so the only time they should really shoot shields without having AP is when there's literally nothing else for them to shoot
