### ISSUE TITLE
Revive Issue (can't reproduce)

### ISSUE THREAD

**Issue by ghost** [segabl/pd2-useful-bots#15]
Currently, the bots will attempt to kill Cloakers and Tazers before attempting a revive. While this is a very useful feature, I think it needs failsafes if it doesn't already have any. I had an issue where the bot was trying to shoot one of them across the map due to the long sightline and so failed to revive me in time before something else killed it.

The two failsafes I was thinking of are a distance check that equals the unit's respective ranges for their special attack and a time check for how long the revive has remaining, having the bot ignore everything if there are only a few seconds left.

**Comment by segabl** [comment]
The following checks are already in place. Bots will not stop moving towards the downed player if
- they are further away from their revive target than 5m
- their health is below half
- the revive timer is below 10s
- the cloaker or taser is further away from them than 10m

these seem to work fine for me, however if you think some of these conditions aren't followed properly let me know

**Comment by segabl** [comment]
I'll check this again but this seemed to be working fine for me

**Comment by segabl** [comment]
Checked again on a test level and all the conditions worked fine on my end
