### ISSUE TITLE
Problems with "Save from Tazer" feature

### ISSUE THREAD

**Issue by IsoiKim** [segabl/pd2-useful-bots#16]
I didn't realize this was even added with the version you gave me until a friend noticed a pattern in the footage I had, but this new feature seems to cause the bots to stay in follow mode even after the situation is resolved until they are either downed or actually told to follow.
### Video of the bug: https://youtu.be/i7nw23Hf6Ck
_Note: In the second clip, we didn't realize he was following for a long time. You can even see my confusion at the end of it._

Another problem is they will move all the way to the player's location first, even if during their move the situation was dealt with. If there's no way to abort their movement immediately once the Tazer is down, I'd like this to be an optional feature, as that could be more problematic to me than having the bot revive me after the fact or having the Tazer give up for no reason like usual. Even if that's possible, this probably should be an optional one.

**Comment by segabl** [comment]
Funnily enough this is not a feature I added but a vanilla one that now works properly cause bots are technically allowed to move now while holding a position. Will look into tweaking the vanilla objective so that it ends properly and the bot can resume to the previous one.

**Comment by segabl** [comment]
This is now properly implemented, delays the assist objective initially so if you free yourself quickly it wont affect bots at all as well as make bots return immediately when you freed yourself instead of finishing the path towards you first.
