### ISSUE TITLE
Navigation issue - San Martin Bank

### ISSUE THREAD

**Issue by ghost** [segabl/pd2-useful-bots#17]
The bots seem to be unable to understand how to hold around the front door of San Martin Bank. I was thinking maybe it's specific to buying "Vlad's Surprise" in preplanning but the location doesn't seem to line up. It's probably due to the hold at player feature but I've managed to get them into some really weird spots so them refusing here is unusual.
### Video of the bug: https://youtu.be/qnKiZRPdZN8
_Note: Second clip is extremely long due to us kinda giving up on getting Hoxton into place. Feel free to skip around._

**Comment by segabl** [comment]
Might be a combination of the AI navigation data around that position and a previous bug where objective position wasnt refreshed if they were already holding a position. Should be fixed with the new version hopefully but its possible that there are just some spots that behave weirdly.

**Comment by segabl** [comment]
yeah they try to take cover from swat turrets even on hold, new version makes them move back to their spots eventually though
