### ISSUE TITLE
Shield lights block bot bullets

### ISSUE THREAD

**Issue by IsoiKim** [segabl/pd2-useful-bots#19]
So the game has a feature, that I assume is left over from when piercing weapons didn't exist, where if you shoot the Shield's lights they get destroyed. This blocks a bullet even if it's a piercing one, but lets you shoot through it once it's destroyed.

Bots on the other hand can't destroy these objects (which I assume was done, so they don't destroy artefacts?). This causes them to sometimes get stuck trying unsuccessfully to shoot through a Shield until either of them moves.

To fix this, either you'll need to find a way to let the bots shoot through breakable objects (which could fix other issues no one noticed if there's actually other breakable objects that block their bullets without breaking line of sight) or you could make a separate ""bugfix"" mod that makes the Shield's lights not block bullets and then mark it as required on Useful Bot's modworkshop page.

**Comment by segabl** [comment]
I fear that breakable objects are pretty deep within raycast weapon code and it's probably not worth overriding the entire hit detection just so it either ignores light objects or lets shots go through it. Also can't say I've noticed this issues at all so far so it must be pretty rare.

**Comment by segabl** [comment]
On your off topic question, you can message me on Discord (Hoppip#1630) or join my Server (https://discord.gg/RJzxGy68Kn) where others may also be able to help when I'm not available. Finally of course there's the MWS Discord (https://discord.gg/Eear4JW) which has dedicated modding/help/request channels.
I'll close this issue as I will most likely not make any changes related to the original topic in this mod itself.
