### ISSUE TITLE
Option to disable bots counting as players (And some strange degrease in bot performance)

### ISSUE THREAD

**Issue by sirben99** [segabl/pd2-useful-bots#2]
Hey!

I like the mod so far, but ive noticed some very steep decline in bot efficiency.

Before i installed, i ran better bots and bot weapon and eguipment mods together. I used the bwe fix teamai balance, and better bots flashbangs, dominate and maskup feature.

I could tell the bots to stay in one stop, and they would hold the position almost the entire heist without problem (I play on overkill with ur randomizer mod for fun, not unlocking achievments etc).

But now when i have Useful Bots installed it seems they go down ever 2 minutes and get overwhelmet every time. Im not sure whats really causing this, but the bots are now even worse and cant even survive with two of them near eachother. I dont and dint have Better Bots combat improvments on, since theyr a bit too good imo.

And yes i have tried without Better Bots mod. (for whatever reason, i dint experience any crashes or bugs when the three bot mods are installed)

It would be nice to have an option to toggle the bots caunting as players, to see if that helps a bit.

Ik this is just for my personal taste. The only thing ive got left to do in the game is about just play random heists with randomizer on and  see what i get XD.

Mods that effect bots used: Useful Bots, Better Bots (With and without), Iter, Bot Weapon and Eguipment and (Maybe?) Streamlined heisting.

I hope you atleast got something out of this, since i cant really explain whats really happening. It just seems that the bots are worse than before when Useful Bots is installed. (Maybe the priority system is at fault too?). I dont mean to offend you or anyone else by this and i hope you werent. I though it would be best that i type what i have experienced as a bit weird.

Cheers!

EDIT: I tweaked the setting a bit and now the bots seem to be much more efficient. It seems the default setting are quite unefficient from my testing. Ill test some more. If youd like screenshots about my settings, please say so!

EDIT 2: It seems that theyr a bit too efficiant now. Clearing everything like no problem. Also they dont dominate enemies anymore, since i put the dominable enemies priority to about 1, wich is lower than everything else.

**Comment by segabl** [comment]
Most of it comes from tweaking the targeting priority, yes. For instance, making the bots focus bulldozers is a bad idea in my experience since they will waste time on the dozers and get swarmed by regular cops in the meantime. The default setting is similar to how vanilla handles it with a few additional tweaks. I will not add an option for disabling bots counting as players since this is meant as a counterbalance to the bot improvements and iirc, better bots does this too. Anyways, you should not use both, Better Bots and this since they will definitely conflict in some areas and lead to unintended behaviour.

**Comment by sirben99** [comment]
Ah okay. Thank you for your anwer! Ill tweak some things then. Do you know if i set the priority to Default, do the bots targed turrets for example? Or does this kinda just ruin everything XD.

**Comment by segabl** [comment]
You mean the base priority? Setting it to default uses the vanilla system and ignores all the other priority settings. They will most likely still attack turrets because that is part of a different function.

**Comment by sirben99** [comment]
Yeah the option Default in the base priority. Ah, im going to tweak it a bit then. Right now its a bit better than vanilla (They can accually kill stuff and stand awhile on theyr own) but they dont dominate enemies (The enemy dominate multiplayer is lowest) and they seem to clear almost everything in theyr path (Enemy that hurt them multiplier is higest). Also the targeting is distance based instead of weapon damage based. 

Since the defaults are more to vanilla, do you have any recomandations for balance between bots that can somewhat survive on theyr own but i get some shooting done too? (Dont shoot the map when enemies spawn, since cop numbers are VERY low, and i sugsect thats the reason). I would assume this is more of an test till you find a good balance for ur playstyle situation.

Other than that, i dont have anything else to add to this. Thank you for taking ur time to answer this! Ill also remove Better Bots even tho i dint have any compability issues, ill take ur sugsection.

Cheers!

**Comment by segabl** [comment]
If you check the screenshots on the mod page, these are the settings I use and find to work quite well, of course it is up to personal preference. Bots will only ever make domination attempts when they are not aware of too many other enemies so there's no problem if you turn up the multiplier, as that multiplier only applies in the same case.

**Comment by sirben99** [comment]
Ill test these settings and see if theyr good for my prefrences. Thank you! I got nothing else to add, so i would say this issue is closed. Have a good day!
