### ISSUE TITLE
Useful bots causing crashes

### ISSUE THREAD

**Issue by Gravesy83** [segabl/pd2-useful-bots#23]
I think there's an issue with the targeting/turning logic (I think it's for the Cloaker, considering the mention of "Spooc"), per the crash.txt I keep getting;

`Application has crashed: C++ exception
[string "lib/units/enemies/cop/logics/coplogicattack.lua"]:1193: attempt to call field 'chk_should_turn' (a nil value)

SCRIPT STACK

_upd_aim() @mods/base/req/core/Hooks.lua:262
force_attention() @mods/pd2-useful-bots-master/lua/teamailogicbase.lua:129
force_attention() @mods/pd2-useful-bots-master/mod.lua:152
func() @mods/pd2-useful-bots-master/lua/actionspooc.lua:8
init() @mods/base/req/core/Hooks.lua:269
new() core/lib/utils/coreclass.lua:35
action_request() lib/units/enemies/cop/copmovement.lua:1133
_chk_request_action_spooc_attack() lib/units/enemies/spooc/logics/spooclogicattack.lua:293
_upd_spooc_attack() lib/units/enemies/spooc/logics/spooclogicattack.lua:233
clbk() lib/units/enemies/spooc/logics/spooclogicattack.lua:141
_execute_queued_task() lib/managers/enemymanager.lua:600
_update_queued_tasks() lib/managers/enemymanager.lua:615
update() lib/managers/enemymanager.lua:52
original() lib/setups/gamesetup.lua:809
update() @mods/base/req/core/Hooks.lua:262
update() lib/setups/networkgamesetup.lua:21
core/lib/setups/coresetup.lua:559

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlGetCurrentDirectory_U                            
                         ntdll  (???)     RtlAnsiStringToUnicodeString                        
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
`

Mod is fully up to date AFAIK, this has been happening since the latest update.

**Comment by segabl** [comment]
Are you using any other bot related mods?

**Comment by Gravesy83** [comment]
Only yours (bot weapons and hoplib).

**Comment by segabl** [comment]
Okay, couldn't reproduce this but it should hopefully not happen anymore with the latest update
