### ISSUE TITLE
Jokers move like bots, bots and jokers can shoot though dominated cops and player can shoot though bots features.

### ISSUE THREAD

**Issue by sirben99** [segabl/pd2-useful-bots#4]
Hey!

I was wondering if any of these would make it to useful bots mod? 

Jokers move like bots: Pretty self explanatory, jokers have the same movement as AI teammates

Bots and jokers shoot though dominated cops: Also self explanatory, less accidental bot killing dominated enemies

Shoot though bots: Im not sure if this is a feature already, but i recall seeing a mod that did this already. It maybe could break some things, but i thought i wanted to hear your input on it

I really enjoy Useful Bots mod and even ditched Better Bots for this one! But Better bots do have some (the upper mentioned) features that would be nice to see in this one, if they go with the scope of the mod. What do you think about these suggestions, and would they fit in the scope of the mod?

Ben

**Comment by segabl** [comment]
Hey, thanks for your suggestions
> Jokers move like bots

is not something I want to add since it's basically just buffing Jokers for no real reason imo

> Bots and jokers shoot though dominated cops

I will think about this, I am not 100% liking the solution of just making them shoot through but given how frustrating it can be when bots shoot hostages, it's something I would be willing to add

> Shoot though bots

There is a mod that does this (https://modworkshop.net/mod/13463) which I use myself but I guess it's something that would fit the mod.

**Comment by sirben99** [comment]
> Hey, thanks for your suggestions
> 
> > Jokers move like bots
> 
> is not something I want to add since it's basically just buffing Jokers for no real reason imo
> 
> > Bots and jokers shoot though dominated cops
> 
> I will think about this, I am not 100% liking the solution of just making them shoot through but given how frustrating it can be when bots shoot hostages, it's something I would be willing to add
> 
> > Shoot though bots
> 
> There is a mod that does this (https://modworkshop.net/mod/13463) which I use myself but I guess it's something that would fit the mod.

Hey!

Sorry for the late responce.

I would like to add to the Jokers move like bots part that i meant that they would keep up with the player better since it seemed there was a delay when they would start moving, but upon further inspection they seem to move just fine on Cookoff. I noticed the delays on Hoxton Breakout day 2, where the jokers would take more than 5 seaconds to register that i moved (or úsing Moonkeepers and waypoints). Im also using Streamlined Heisting, so maybe its map specific or Streamlined improved theyr delays.

Thank you for listening to my sugsections!

Ben

**Comment by segabl** [comment]
The reason why jokers take longer to move is that they still have to adhere to the enemy task limit. So with a lot of active tasks, their movement is delayed.
Seeing as the other features are implemented now, I'm gonna go ahead and close this issue.
