### ISSUE TITLE
PAYDAY 2 crashes to desktop when handcuffed (by Cloakers in Holdout mode)

### ISSUE THREAD

**Issue by Biblioklept** [segabl/pd2-useful-bots#8]
Title's the problem, happens everytime I get handcuffed by a Cloaker in Holdout mode.
[crash.txt](https://github.com/segabl/pd2-useful-bots/files/9034511/crash.txt)

**Comment by segabl** [comment]
thank you for the report, will try to fix this soon

**Comment by segabl** [comment]
Should be fixed in 5db53b03f8d361d79ae5aa185e90951f714d898c
